---
title: "Stitch Fix Outfit Detection"
output: html_notebook
---


```{r}
library(tidyverse)
library(caret)
library(patchwork)
library(plotROC)
library(pROC)
library(ggrepel)
library(grid)
library(gridExtra)


set.seed(888) # To ensure consistent results from non-deterministic procedures
rm(list = ls()) # Removes all variables

```


```{r read_data}
SF.df = read_csv("StitchFix.csv")

# SF.df = data_frame(obs = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
#                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 
#                   pred = c(.9, .8, .3, .9, .8, .7, .8, .8, .4, .9, .6, .7, 
#                            .1, .1, .2, .7, .4, .5, .3, .1, .2, .6, .4, .4 ))

```

```{r calculate_fpFn_confusion}
threshold = .5

confusion_matrix.obj = confusionMatrix(data = as.factor(SF.df$pred > threshold), 
                reference = as.factor(SF.df$obs == 1), 
                positive = "TRUE")

confusion_matrix.df = confusion_matrix.obj$table %>% 
  data.frame() %>% 
 # mutate(PredictionF = factor(as.factor(Prediction), levels = c("Present", "Absent"))) %>%
  group_by(Reference) %>% 
  mutate(total = sum(Freq)) %>% 
  ungroup()

ggplot(confusion_matrix.df, aes(Reference, Prediction)) +
  geom_tile(aes(fill = Freq/total)) +
  geom_label(aes(label = round(Freq/total, 2))) +
  scale_fill_gradient(low = "grey90", high = "grey10",guide = FALSE) 

## Add threshold to all rows
tp_fp_threshold.df = SF.df %>% rowwise() %>% 
  mutate(threshold = list(seq(from = 0, to = 1, by = .1))) %>%
  unnest(cols = c(threshold))

## Calculate true positive and false positve fraction for all thresholds
tp_fp_threshold.df = tp_fp_threshold.df %>% group_by(threshold) %>% 
  summarise(total_obs1 = sum(obs == 1),
            total_obs0 = sum(obs == 0),
            tp = sum(obs == 1 & pred >= threshold)/total_obs1,
            fp = sum(obs == 0 & pred >= threshold)/total_obs0)

```


```{r outfit_roc}

t = .5
SF.roc = roc(predictor = SF.df$pred, 
              response = SF.df$obs, 
              AUC = TRUE, ci = TRUE)
SF.roc$auc

print(SF.roc$auc)


tp_fp.df = tp_fp_threshold.df %>% filter(near(threshold, t)) # Filter based on slider
        
        tp.plot = ggplot(SF.df %>% filter(obs == 1),
                         aes(x = pred)) + 
            annotate("rect", xmin = Inf, xmax =  tp_fp.df$threshold, ymin = -Inf, ymax = tp_fp.df$tp, 
                     colour = "grey80", alpha = .2) +
            geom_vline(xintercept = tp_fp.df$threshold, colour = "darkgrey") +
            geom_hline(yintercept = tp_fp.df$tp, colour = "darkred") +
            stat_ecdf(geom = "step") +
            geom_dotplot(binwidth = .1, dotsize = .5, stackgroups = TRUE, 
                         method = "dotdensity", binpositions = "all") +
            geom_label_repel(data = SF.df %>% filter(obs == 1) %>% filter(pred==min(pred)) %>% slice(1), 
                            aes(pred, y = 0), label = "Incorrectly confident in absence", 
                            nudge_y = .2) +
            coord_equal() +
            lims(y = c(0, 1)) +
            scale_x_reverse(limits = c(1, 0)) +
            labs(x = "Strength of evidence", y = "True positive fraction", title = "Positive cases") +
            theme(plot.margin = margin(0, 0, 0, 0, "cm"))
        
        
        fp.plot = ggplot(SF.df %>% filter(obs == 0),
                         aes(x = pred)) + 
            annotate("rect", xmin = Inf, xmax =  tp_fp.df$threshold, ymin = -Inf, ymax = tp_fp.df$fp, 
                     colour = "grey80", alpha = .2) +
            geom_vline(xintercept = tp_fp.df$threshold, colour = "darkgrey") +
            geom_hline(yintercept = tp_fp.df$fp, colour = "darkred") +
            stat_ecdf(geom = "step") +
            geom_dotplot(binwidth = .1, dotsize = .5, stackgroups = TRUE, fill = "white", binpositions = "all") +
            geom_label_repel(data = SF.df %>% filter(obs == 1&pred==max(pred)) %>% slice(1), 
                            aes(pred, y = 0), label = "Incorrectly confident in presence", 
                            nudge_x = -.2) +
            coord_equal() +
            coord_flip() +

            lims(x = c(0, 1), y = c(0, 1)) +
            labs(x = "Strength of evidence", y = "False positive fraction", title = "Negative cases") +
            theme(plot.margin = margin(0, 0, .1, .1, "cm"))
        
        
        roc.plot =ggplot(data = SF.df, aes(d = obs, m = pred)) + 
            geom_abline(colour = "grey60") +
            geom_hline(yintercept = tp_fp.df$tp, colour = "darkred") +
            geom_vline(xintercept = tp_fp.df$fp, colour = "darkred") +
            geom_roc(linealpha = .5, pointalpha = .5, labels = TRUE, labelsize = 3) +
            annotate("point", y = tp_fp.df$tp, x = tp_fp.df$fp, colour = "darkred", size = 3) +
            annotate("text", x = .5, y = .375, hjust = 0,
                     label = paste("AUC =", round(SF.roc$auc, 2))) +
            coord_equal() +
            labs(x = "", y = "", title = "ROC Curve") +
            theme(plot.margin = margin(0, 0, 0,0, "cm"))
    

        
confusion_matrix.obj = confusionMatrix(
  data = as.factor(SF.df$pred > threshold), 
  reference = as.factor(SF.df$obs == 1), 
  positive = "TRUE")

confusion.df = data.frame(confusion_matrix.obj$table)
confusion.df$Label = c("TN", "FP", "FN", "TP")


confusion.plot = ggplot(confusion.df, 
                        aes(reorder(Reference, desc(Reference)), Prediction, fill = Freq, label = Freq)) +
  geom_tile() +
  geom_label(fill = "lightgrey", size = 2) +
  geom_label(aes(label = Label), fill = "lightgrey", nudge_y = .2, size = 2) +
  labs(x = "Reference") +
  theme_minimal() +
  scale_fill_gradient(low = "grey90", high = "grey10") +
  theme(legend.position = "none") 
confusion.plot


measure.df = data.frame(Value = confusion_matrix.obj$byClass) %>% 
  rownames_to_column(var = "Metric") %>% 
  mutate(Value = round(Value, 2)) %>% 
  slice(1:6)

tt = ttheme_default(colhead = list(fg_params = list(parse = TRUE)), base_size = 8)
roc.table <- tableGrob(measure.df, rows = NULL, theme = tt)
      
roc.table = wrap_elements(panel = roc.table)
    
combined.plot = tp.plot + roc.plot +
                (confusion.plot/roc.table) + fp.plot +
                plot_layout(ncol = 2)
combined.plot

```



